# Generated by Django 5.1.6 on 2025-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anemometers', '0002_rename_elevation_anemometer_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometertag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
