# Generated by Django 5.1.6 on 2025-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anemometers', '0003_alter_anemometertag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anemometer',
            name='measurement_unit',
        ),
    ]
